[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
no_custodial_escrow = "AV3c98nRRqN14J27CRZuWsKrZ3RQDtNha8gtRXQtCk6v"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# wallet = "~/.config/solana/id.json"
wallet = "~/.config/solana/vt_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
