[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_voting = "G6rDtj4f3KSNRXZUytAF9Qs2w5FqpDRPzZs7UD7ScMbL"

[programs.devnet]
onchain_voting = "G6rDtj4f3KSNRXZUytAF9Qs2w5FqpDRPzZs7UD7ScMbL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# wallet = "~/.config/solana/id.json"
wallet = "~/.config/solana/vt_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
